name: Backend Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  TAG: "1.0.0"

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      working-directory: backend
      run: docker build . --file Dockerfile --tag fuel-prices-agent-backend:${{ env.TAG }}
    - name: Login Docker to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Tag the Docker image
      run: docker tag fuel-prices-agent-backend:${{ env.TAG }} ghcr.io/${{ github.repository }}:${{ env.TAG }}
    - name: Push the Docker image
      run: docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}